# Generated by Django 4.1.7 on 2023-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer')], max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Mathematics')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Earned', 'Earned')], max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved_HOD', models.BooleanField(default=False)),
                ('is_approved_AR', models.BooleanField(default=False)),
                ('is_approved_DIRECTOR', models.BooleanField(default=False)),
            ],
        ),
    ]
